CREATE TABLE [catalogo].[PRODUCTO]
(
[NUMEROPRODUCTO] [int] NOT NULL,
[NOMBREPRODUCTO] [varchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[STOCKPRODUCTO] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [catalogo].[PRODUCTO] ADD CONSTRAINT [PK_PRODUCTO] PRIMARY KEY CLUSTERED  ([NUMEROPRODUCTO]) ON [PRIMARY]
GO
