CREATE TABLE [movimientos].[PRODUCCION]
(
[NUMEROPRODUCTO] [int] NULL,
[NUMEROFABRICA] [int] NULL,
[CANTIDADPRODUCTO] [int] NOT NULL,
[FECHAELABORACION] [date] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [movimientos].[PRODUCCION] ADD CONSTRAINT [Tiene] FOREIGN KEY ([NUMEROFABRICA]) REFERENCES [catalogo].[FABRICA] ([NUMEROFABRICA])
GO
