CREATE TABLE [catalogo].[FABRICA]
(
[NUMEROFABRICA] [int] NOT NULL,
[NOMBREFABRICA] [varchar] (250) COLLATE Modern_Spanish_CI_AS NOT NULL,
[TELEFONO] [varchar] (25) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [catalogo].[FABRICA] ADD CONSTRAINT [PK_FABRICA] PRIMARY KEY CLUSTERED  ([NUMEROFABRICA]) ON [PRIMARY]
GO
